### ISSUE TITLE
Sortable object cannot accept a tuple [or other iterators]?

### ISSUE THREAD

**Issue by kezabelle** [drewyeaton/django-sortable#1]
[Line 46](https://github.com/drewyeaton/django-sortable/blob/master/sortable.py#L46) of **sortable.py** (`sortable.Sortable.sorted()`) should, at the very least, support passing in a tuple, I think.

```
>>> a = (1, 2, 3, 4, 5)
>>> isinstance(a, list)
False
>>> isinstance(a, tuple)
True
>>> isinstance(a, (list, tuple))
True
>>> sorted(a, reverse=True)
[5, 4, 3, 2, 1]
```

Filed because you asked for feedback [on reddit](http://www.reddit.com/r/reviewmycode/comments/qxx12/python_django_sorting_library_that_works_with/), which serves as a useless ticket tracker :)

**Comment by drewyeaton** [comment]
Good suggestion!
